phpmd-ansi:
	@php ./vendor/bin/phpmd ./Core ansi --color  ./rulesets.xml

phpmd-text:
	@php ./vendor/bin/phpmd ./Core text --color  ./rulesets.xml

phpmd-json:
	@php ./vendor/bin/phpmd ./Core json --color  ./rulesets.xml