name: A workflow for my Hello World file
on: [push, pull_request]
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - name: npm install and build webpack
      run: echo "{{ MY_NAME }}"
    
