# This is a basic workflow to help you get started with Actions

name: Scheduled 15 Min

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron:  '*/15 * * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
        required: true
        default: 'warning'
      myInput:
        description: 'My Input'
        required: true
        default: 'I got it!'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Run a multi-line script (curl)
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Maykon-JDS/math-function-calculator-api/dispatches \
          -d '{"event_type":"repositoryDispatchWorkflow"}'

      - name: Run a multi-line script (gn)
          # GitHub CLI api
          # https://cli.github.com/manual/gh_api
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/Maykon-JDS/math-function-calculator-api/dispatches \
            -f "event_type=repositoryDispatchWorkflow"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
